[fix] gihp\Parser\File::exportAnnotatedTag()
Error: PHP Fatal error:  Call to undefined method gihp\Object\Commit::getTypeString()

 * Add new method gihp\Parser\File::getObjectTypeString() to look up the type of an object
 * Let gihp\Parser\File::exportAnnotatedTag() use this new method
 * gihp\Parser\File::exportObject() logic was similar, refactor to also use self::getObjectTypeString()